In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
##apply label encoder on gender
label_encode_gender = LabelEncoder()
data['Gender'] = label_encode_gender.fit_transform(data['Gender'])
data['Gender'].value_counts()

1    5457
0    4543
Name: Gender, dtype: int64

In [6]:
##Applying OneHotEncoder on Geography column
from sklearn.preprocessing import OneHotEncoder
One_hot_encoder = OneHotEncoder()
geo_encoder = One_hot_encoder.fit_transform(data[['Geography']])
geo_encoder

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [7]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(),columns=One_hot_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
## combining geograph_encoded_df with the original
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
##Split into independent and dependent
X = data.drop('EstimatedSalary',axis=1)
Y = data['EstimatedSalary']

In [10]:
## split into training and testing and apply standard scalar
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [11]:
## Scale
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [12]:
## save the encoder and scalar
with open('Label_encoder_gender_reg.pkl','wb') as file:
    pickle.dump(label_encode_gender,file)
    
with open('Onehot_encoder_geo_reg.pkl','wb') as file:
    pickle.dump(One_hot_encoder,file)
    
with open('scalar_reg.pkl','wb') as file:
    pickle.dump(scalar, file)

In [13]:
## train our model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [15]:
## Let's build Our Model

model = Sequential([
    Input(shape=(X_train.shape[1],)),  # Explicit Input layer
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1) ## by default its linear
])
## compile
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
## set up the tensorboard to visualize training
log_dir = "regression_log/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [17]:
### Set up Early Stopping --->> after certain epochs if loss function is not decreasing we can stop it there
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [18]:
### Training the model
history = model .fit(
    X_train,Y_train,
    validation_data=(X_test,Y_test),
    epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - loss: 99964.8906 - mae: 99964.8906 - val_loss: 98488.1562 - val_mae: 98488.1562
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 100210.7266 - mae: 100210.7266 - val_loss: 96762.6953 - val_mae: 96762.6953
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 98424.2578 - mae: 98424.2578 - val_loss: 92399.5078 - val_mae: 92399.5078
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 92075.9766 - mae: 92075.9766 - val_loss: 85211.9141 - val_mae: 85211.9141
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 85055.1094 - mae: 85055.1094 - val_loss: 76150.9062 - val_mae: 76150.9062
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 73745.4297 - mae: 73745.4297 - val_loss: 66992.5078 - val_mae: 66992.5078
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 66215.9219 - mae: 66215.9219 - val_loss: 59403.3438 - val_mae: 59403.3438
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 57799.1133 - mae: 57799.1133 - val_loss: 54379.6992 - val_mae: 54379.6992
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 53584.0703 - mae: 53584.0703 - val_loss: 51799.4062 - val_mae: 51799.4062
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 51993.2695 - mae: 51993.2695 - val_loss: 50855.2344 - val_mae: 50855.2344
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50223.1211 - mae: 50223.1211 - val_loss: 50574.6836 - val_mae: 50574.6836
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50343.4531 - mae: 50343.4531 - val_loss: 50497.5000 - val_mae: 50497.5000
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50161.9141 - mae: 50161.9141 - val_loss: 50453.7812 - val_mae: 50453.7812
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50370.0508 - mae: 50370.0508 - val_loss: 50415.6797 - val_mae: 50415.6797
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50288.8047 - mae: 50288.8047 - val_loss: 50383.5781 - val_mae: 50383.5781
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49822.4141 - mae: 49822.4141 - val_loss: 50357.3008 - val_mae: 50357.3008
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49640.4805 - mae: 49640.4805 - val_loss: 50331.8945 - val_mae: 50331.8945
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50790.6602 - mae: 50790.6602 - val_loss: 50326.2969 - val_mae: 50326.2969
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50730.5625 - mae: 50730.5625 - val_loss: 50300.5078 - val_mae: 50300.5078
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49542.4219 - mae: 49542.4219 - val_loss: 50281.3516 - val_mae: 50281.3516
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49697.9141 - mae: 49697.9141 - val_loss: 50268.6367 - val_mae: 50268.6367
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49960.5586 - mae: 49960.5586 - val_loss: 50260.4102 - val_mae: 50260.4102
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49924.4609 - mae: 49924.4609 - val_loss: 50253.2031 - val_mae: 50253.2031
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49721.3711 - mae: 49721.3711 - val_loss: 50243.4922 - val_mae: 50243.4922
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50190.3984 - mae: 50190.3984 - val_loss: 50235.0508 - val_mae: 50235.0508
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50128.8906 - mae: 50128.8906 - val_loss: 50225.7031 - val_mae: 50225.7031
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49757.7266 - mae: 49757.7266 - val_loss: 50212.1445 - val_mae: 50212.1445
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49441.6250 - mae: 49441.6250 - val_loss: 50208.5664 - val_mae: 50208.5664
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49588.4922 - mae: 49588.4922 - val_loss: 50201.2461 - val_mae: 50201.2461
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49138.3281 - mae: 49138.3281 - val_loss: 50195.0312 - val_mae: 50195.0312
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49341.7500 - mae: 49341.7500 - val_loss: 50190.1953 - val_mae: 50190.1953
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49366.6289 - mae: 49366.6289 - val_loss: 50177.4766 - val_mae: 50177.4766
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49861.0117 - mae: 49861.0117 - val_loss: 50170.4414 - val_mae: 50170.4414
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49640.5625 - mae: 49640.5625 - val_loss: 50175.6641 - val_mae: 50175.6641
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49405.4414 - mae: 49405.4414 - val_loss: 50180.1445 - val_mae: 50180.1445
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49231.5508 - mae: 49231.5508 - val_loss: 50194.8242 - val_mae: 50194.8242
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 50271.5820 - mae: 50271.5820 - val_loss: 50177.6484 - val_mae: 50177.6484
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 50094.2539 - mae: 50094.2539 - val_loss: 50183.5977 - val_mae: 50183.5977
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49193.0039 - mae: 49193.0039 - val_loss: 50188.4453 - val_mae: 50188.4453
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49263.0078 - mae: 49263.0078 - val_loss: 50192.4766 - val_mae: 50192.4766
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49657.0977 - mae: 49657.0977 - val_loss: 50182.5781 - val_mae: 50182.5781
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49809.8945 - mae: 49809.8945 - val_loss: 50192.2227 - val_mae: 50192.2227
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50281.7188 - mae: 50281.7188 - val_loss: 50177.3438 - val_mae: 50177.3438

In [19]:
##Load Tensorboard Extension
%load_ext tensorboard

In [22]:
%tensorboard --logdir regression_log/fit20250502-100526

In [23]:
## evalutate the model
test_loss , test_mae = model.evaluate(X_test,Y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 51038.0195 - mae: 51038.0195

In [24]:
model.save('regression_model.keras')